### ISSUE TITLE
개발항목 정하기

### ISSUE THREAD

**Issue by eunhyulkim** [transcendentalists/ninza#1]
1. 채팅
2. 퐁 게임
3. 회원가입/로그인
    - 42인증, 구글/페이스북 인증
4. 사이드바
    - 접속 상태 확인
    - 친구 추가
    - DM
    - 듀얼 신청
5. 길드 페이지
    - 길드 가입
    - 길드 랭킹
    - 길드 정보
6. 채팅 채널
7. 레더 시스템 설계 및 랭킹 페이지
8. 게임 구현
    - 토너먼트
    - 승급전
    - 길드전
9. 관리자 페이지
    - Service owner와 Web admin을 위한 페이지

**Comment by humblEgo** [comment]
1. 채팅
    1. **채팅 채널과 DM을 기능적으로 분리하는 안 ✅**

        ```jsx
        단체 채팅방이 메인뷰에 리스트로 보이고,
        DM은 사이드바에 리스트로 보인다.
        ```

    2. 채팅 채널과 DM을 기능적으로 통합하되 UI적으로 분리하는 안

        ```jsx
        단체 채팅방이든 DM이든 메인뷰에 리스트로 보인다.
        ```

2. 퐁 게임
    - 게임할 때에는 게임만 가능하도록 처리
3. 회원가입/로그인
    - 42인증, 구글/페이스북 인증
4. 사이드바
    - 접속 상태 확인
    - 친구 추가
    - DM
    - 듀얼 신청
5. 길드 페이지
    - 길드 가입
    - 길드 랭킹
    - 길드 정보
6. 채팅 채널
7. 레더 시스템 설계 및 랭킹 페이지
8. 게임 구현
    - 토너먼트
    - 승급전
    - 길드전
